var vm=new Vue({
    el:"#home",
    data:{
        barber_select:"",
        taocan_select:"",
        selected:"洗发",
        price:"",
        options:[
        ],
        barbers:[],
        times:[
            {text:"10:20-11:00",value:"time_one"},
            {text:"11:30-12:00",value:"time_two"},
            {text:"14:00-15:00",value:"time_three"},
        ],
        pays:[
            {text:"现金支付",value:"pay_one"},
            {text:"微信支付",value:"pay_two"},
            {text:"支付宝",value:"pay_three"},
        ]
    },
    methods:{
        getData:function (datas){
            this.$http.get("http://localhost:11162/api/v1/account/allBarber").then(function(data){
                this.barbers=data.body;
                this.barber_select=this.barbers[0].Name;
            })
        },
        gettaocan:function(datas){
            this.$http.get("http://localhost:11162/api/v1/package/all?pa=1").then(function(data){
            this.options=data.body;
            this.taocan_select=this.options[0].Name;
            })
        },
        yuyue:function(){
            alert(this.barber_select);
        },
    },
    created:function(){
        this.getData();
        this.gettaocan();
    },
})