var vue=new Vue({
    el:"#publish_home",
    data:{
        content:"",
        img_url:"",
    },
    methods:{
        user_login:function(){
            if(window.localStorage.length==0){
                alert("请先登录");
                window.location.href="login.html";
            }
        },
        return_publish:function(){
            window.location.href="share.html"
        },
        submit_publish:function(){
            alert(this.content);
            alert(this.img_url);
            alert("保存成功");
        }
    },
    created:function(){
        this.user_login();
    }
})