var vm=new Vue({
    el:"#home",
    data:{
        infomations:[],
        name:"",
        username:'',
        phone:"",
        email:"",
        username:"",
        introduce:"",
        userid:"",
        if_phone_error:false,
        if_email_error:false,
        phone_error:"",
        email_error:"",
        readonly:true,
        isedit:false,
        noedit:true,
        if_phone_error:false,
        edit_info:true,
        edit_qued:false,
    },
    methods:{
        show:function(){
            this.edit_info=false;
            this.edit_qued=true;
            this.noedit=false;
            this.isedit=true;
            this.readonly=false
        },
        look_order:function(){
            window.location.href="look_my_order.html";
        },
        look_share:function(){
            window.location.href="look_my_share.html";
        },
        look_info:function(){
            window.location.href="user_info.html";
        },
        cancel:function(){
            window.location.reload();
        },
        save:function(){
            if(this.if_phone_error==false&&this.if_email_error==false)
            {
                this.$http.put('http://localhost:11162/api/v1/account',{
                        Id:this.userid,
                        Name:this.username,
                        PhoneNumber:this.phone,
                        Email:this.email,
                        PersonalInfo:this.introduce,
                    },
                    {headers:{token:localStorage.getItem("userId")}},
                    {emulateJSON:true}                   
                ).then(function(data){
                    console.log(data);
                    this.name=data.body.Name;
                    this.phone=data.body.PhoneNumber;
                    this.email=data.body.Email;
                    this.PersonalInfo=data.body.PersonalInfo;
                })
                this.noedit=true;
                this.isedit=false;
                this.readonly=true
            }
            else
            {
                alert("lalas");
            }
        },
        phone_istrue:function(){
              var telepehone = /^1\d{10}$/; //手机号的正则表达式
              if(!telepehone.test(this.phone)){
                  this.phone_error="请验证手机号";
                  this.if_phone_error=true;
              }
              else
              {
                  this.if_phone_error=false;
              }
        },
        email_istrue:function(){
              var emai = /^(\w-*\.*)+@(\w-?)+(\.\w{2,})+$/; //邮箱的正则表达式
              if(!emai.test(this.email)){
                  this.if_email_error=true;
                  this.email_error="请输入正确的邮箱格式";
              }
              else
              {
                  this.if_email_error=false;
              }
        },
        get_info:function(){
            if(localStorage.length!=0){
                this.name=localStorage.getItem("username");
                this.$http({
                     method:'GET',
                     headers:{token:localStorage.getItem("userId")},
                     url:"http://localhost:11162/api/v1/account",
                }).then(function(data){
                    this.infomations=data.body;
                    console.log(this.infomations);
                    this.userid=this.infomations.Id;
                    this.username=this.infomations.Name;
                    this.barbername=this.name;
                    this.phone=this.infomations.PhoneNumber;
                    this.email=this.infomations.Email;
                    this.introduce=this.infomations.PersonalInfo;
                },function(res){
                    console.log(res);
                    alert(res.message);
                })
            }
            else{
                alert("请先登录!");
                window.location.href="login.html";
            }
        },
        login_out:function(){
            localStorage.clear();
            window.location.href="login.html";
        },
    },
    created:function(data){
        this.get_info();
    }
})